#pragma once

#define GP_BUILD_VERSION_MAJOR 1
#define GP_BUILD_VERSION_MINOR 1
#define GP_BUILD_VERSION_UPDATE 3

#define GP_APPLICATION_VERSION_STRING "1.1.3"
#define GP_APPLICATION_COPYRIGHT_STRING "2019-2022 Gale Force Games LLC"
#define GP_APPLICATION_WEBSITE_STRING "https://github.com/elasota/Aerofoil"
