ln -sf ../../../AerofoilPortable .
ln -sf ../../../AerofoilSDL .
ln -sf ../../../GpCommon .
ln -sf ../../../GpApp .
ln -sf ../../../GpShell .
ln -sf ../../../MacRomanConversion .
ln -sf ../../../PortabilityLayer .
ln -sf ../../../rapidjson .
ln -sf ../../../stb .
ln -sf ../../../SDL2-2.32.6 SDL2